development:
  adapter: postgresql
  encoding: unicode
  database: amua_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: amua_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: amua_production
  pool: 5
